pyuic4 mainUi.ui -o mainUi.py
pyuic4 tab_markersUi.ui -o tab_markersUi.py
pyuic4 tab_objectsUi.ui -o tab_objectsUi.py
pyuic4 tab_regionsUi.ui -o tab_regionsUi.py
pyuic4 tab_serialUi.ui -o tab_serialUi.py
pyuic4 tab_blindspotUi.ui -o tab_blindspotUi.py
pyuic4 tab_calibrationUi.ui -o tab_calibrationUi.py
pyuic4 statusBarUi.ui -o statusBarUi.py
pyuic4 arduino_indicator_widget.ui -o arduino_indicator_widget.py
pyrcc4 icons.qrc -o icons_rc.py
